### ISSUE TITLE
Why need home directory ?

### ISSUE THREAD

**Issue by onmyway133** [technicalpickles/homesick#119]
Many dotfiles projects on github do not have home directory

**Comment by smcabrera** [comment]
@onmyway133 You could achieve the same thing though by forking that dotfiles repo you're interested in, adding the home folder to make it a castle and then pulling from your fork if you want to get updates. You should end up with the same functionality in in the end.

**Comment by JCook21** [comment]
I'm going to close this issue. Feel free to reopen it if you think it needs to be.
