### ISSUE TITLE
Add possibility to unlink single file

### ISSUE THREAD

**Issue by raffomania** [technicalpickles/homesick#126]
Title says it all. I'd like to unlink and then remove files from my castle.

**Comment by RantSomeWhere** [comment]
Just bumping this issue again.

**Comment by JCook21** [comment]
I'm going to close this one as I think this can be done without adding new commands to Homesick. You can remove the symlink just using rm in your shell. You can then do `homesick cd CASTLE` to open a shell in the root of the castle, followed by git rm to remove it.

Please feel free to reopen this issue if there's a use case I've missed.
