### ISSUE TITLE
Rename / move file

### ISSUE THREAD

**Issue by cirosantilli** [technicalpickles/homesick#131]
I would like to do:

```
homesick move src dst
```

and have:
- `git mv` be done (may require directory creation + update of `.homesick_subdir`)
- symlink get moved and point to the new correct file

I see that config files don't move around often: my use case is for tracking my `~/bin`, where I may arbitrarily decide to rename a script.

**Comment by JCook21** [comment]
Could you achieve something similar using the exec and exec_all commands?

**Comment by cirosantilli** [comment]
@JCook21 not directly with `exec` since you'd have to recreate the symlink outside of the repository to point to the new location in the repository.

Of course, I could write a small script that does it. But I think that the small script would be long enough / useful enough that it's worth adding it here.

In particular, the script would have to deal properly with the `.homesick_subdir` file which is a bit "internalish" and would fit better in the library itself. Nothing unsurmountable though.

**Comment by JCook21** [comment]
@cirosantilli what if we added the ability to link and unlink single files in a repo? That would allow you to unlink a file, use `homesick exec` or `homesick cd` to perform the git move and the relink the file afterwards. Does that sound viable? I hesitate to add a move command to homesick if it's really only to cover an edge case. I'd be interested to hear any other thoughts on this from others though...

**Comment by cirosantilli** [comment]
@JCook21 I almost wrote that in this request. It would make it simple to write a 3 command bash alias that does the move then.

I understand that those use cases are not major.

**Comment by JCook21** [comment]
@cirosantilli sounds like we're on the same page. I think I started looking into this functionality in a branch somewhere, let me see if I can dig it up. If you have some code ready feel free to submit a PR too.

**Comment by JCook21** [comment]
I'm going to close this issue as I feel that this could be achieved using the following workflow:

- delete the symlink in the home directory
- perform the `git mv`, perhaps using `homesick cd` or `homesick exec` to help
- run `homesick link` again, skipping the files that are already linked

Feel free to open this again if I've missed something.
