### ISSUE TITLE
Add fetch command

### ISSUE THREAD

**Issue by Kidlike** [technicalpickles/homesick#132]
I would like to have the `git fetch` command available through homesick.
This way I can do a `homesick fetch` to see if I am behind from the remote.

I have a homesick-all function in my [bash functions](https://github.com/Kidlike/homesick-bash/blob/master/home/.bash_functions) that will run the provided homesick arguments for all castles.

So then I could do a `homesick-all fetch` and immediately see if any of my castles need updating.

**Comment by Kidlike** [comment]
I just realized that the new version has a -all switch for some commands, so hopefully my bash function will eventually become obsolete :)

**Comment by JCook21** [comment]
As mentioned in the comments on #135

**Comment by JCook21** [comment]
As mentioned in the comments on #135 this can be achieved through the exec_all command.

**Comment by Kidlike** [comment]
Closed as per #135
