### ISSUE TITLE
Automatically accepting overwrites

### ISSUE THREAD

**Issue by smcabrera** [technicalpickles/homesick#138]
I'm trying to use homesick as part of an ansible playbook to automatically provision development environments for me. It works quite well in this respect--making it easier for me to clone the dotfiles. However one place where this snags is when I would be getting the prompt that I'll be overwriting existing dotfiles, I can't make a selection with ansible.

If I could just pass in an additional option to automatically overwrite (the way this works for  ```apt``` for instance) then I could just include this line in my script:

````
homesick symlink dotfiles -Y
````

and I would be able to automate it much more simply. Would this be feasible/simple to do ?

**Comment by technicalpickles** [comment]
There is `--force` option to always override. I think that should do what you are looking for.

**Comment by smcabrera** [comment]
Ah ok that should work. Thanks!
