### ISSUE TITLE
add option for castle name to clone

### ISSUE THREAD

**Issue by rweng** [technicalpickles/homesick#141]
I would like to prefix my github repositories with `homesick-` so they can be better found and distinguished. On the other hand, when in my terminal, I don't want to have this prefix. I suggest adding an option to clone to set the clone destination / castle name, as can be done via git clone.

**Comment by JCook21** [comment]
I'm open to this and do you have any implementation suggestions? At the moment homesick relies on convention to know where to find castles. I think we'd need to store castle names and locations somewhere if we make this change.

**Comment by rweng** [comment]
Hmm, I don't think so, but I might be wrong as I started today w/ homesick :) But from my understanding the directory name is the castle name, so all that would have to be adjusted is that a name can be given to `git clone`. I experimented w/ adjusting the remote-url which seemed to work fine, and afaik git clone REPO name would be nothing else that that. In that case, implementation would be as simple as to add an option to the cli and pass it down to [clone](https://github.com/technicalpickles/homesick/blob/master/lib/homesick/cli.rb#L43), which could still keep the existing logic for determining the destination as default.

But as always, I might be wrong :)

**Comment by JCook21** [comment]
Fair point, I think you may well be right. Do you have time to experiment with this?

**Comment by rweng** [comment]
damn, didn't link it to this issue. Anyway, created a pull request which seems to work: https://github.com/technicalpickles/homesick/pull/144

**Comment by JCook21** [comment]
Closing this issue as the PR has now been merged. :)
