### ISSUE TITLE
need to input username and password everytime

### ISSUE THREAD

**Issue by chengyi818** [technicalpickles/homesick#150]
When I want to push my changes to github repos,I need to input username and password everytime.
Is there any method,I can skip this step.:smile:

**Comment by nicolasmccurdy** [comment]
https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by chengyi818** [comment]
@nicolasmccurdy thanks,this method can cache password for a few minutes.
When I clone my github repos to my own PC and push some commits,I never need to input password.
so can I config homesick which makes me never need to input password?
my id_rsa.pub has already in my github settings.:kissing_heart:

**Comment by nicolasmccurdy** [comment]
There are multiple git protocols, including SSH and HTTPS, which handle authentication differently. It seems like you're saving your password for one of them but homesick is using a different protocol.

**Comment by JCook21** [comment]
Homesick passes all git operations directly through to the git installation on your terminal. For that reason I'm inclined to agree with @nicolasmccurdy and say this is probably down to a difference in how SSH and HTTPS protocols are handled. I'm going to close this but if you can add more info about how this might be a bug in Homesick feel free to reopen this.
