### ISSUE TITLE
Homesick symlinks local git repository instead of cloning it.

### ISSUE THREAD

**Issue by hjri** [technicalpickles/homesick#151]
Currently when you try to clone local repository homesick symlinks it and this leads to broken homesick_subdir behaviour.

Common usecase: I have dotfiles for my user and I want to have same dotfiles when I'm logged it as root. I cannot clone remote repository because I'd need ssh keys\login-password set up for root, so I just clone local directory and pull changes from there.

**Comment by JCook21** [comment]
Can you be more specific about how things are broken? The more info you can give the better I'll be able to see what's going on.

**Comment by JCook21** [comment]
I'm going to close this issue due to the lack of further information. I'm also wondering if `sudo -s` might give you the answer to what you're looking for. Feel free to reopen this if I've missed a use case.
