### ISSUE TITLE
Incorrect version reported for release gem v1.1.4

### ISSUE THREAD

**Issue by JoeNyland** [technicalpickles/homesick#160]
From https://github.com/technicalpickles/homesick/issues/156#issuecomment-288694900

I've upgraded to 1.1.4 and I noticed the following issue:

```
gem list homesick

*** LOCAL GEMS ***

homesick (1.1.4)
```
```
homesick version
1.1.3
```
```
cat ~/.rvm/gems/ruby-2.3.3/gems/homesick-1.1.4/lib/homesick/version.rb
# -*- encoding : utf-8 -*-
module Homesick
  # A representation of Homesick's version number in constants, including a
  # String of the entire version number
  module Version
    MAJOR = 1
    MINOR = 1
    PATCH = 3

    STRING = [MAJOR, MINOR, PATCH].compact.join('.')
  end
end
```

Seems like 0d60ae9d1acf8a115203efcf57b3a71f75039d70 wasn't included in the built gem that was uploaded to RubyGems.org?

**Comment by JCook21** [comment]
This should now be fixed. I've just release v 1.1.5 and have verified that the version number is correct. Thanks for reporting this.
