### ISSUE TITLE
homesick clone failure isn't handled properly

### ISSUE THREAD

**Issue by dergachev** [technicalpickles/homesick#25]
I've noticed that "homesick clone GITPATH" often fails silently, outputting the exact message as when it succeeds. The following occurs on a system with no git installed:

``` bash
alex@precise64:~$ homesick clone git://github.com/technicalpickles/dotpickles.git
   git clone  git://github.com/technicalpickles/dotpickles.git to /home/alex/.homesick/repos/dotpickles
```

The same behavior occurs if the repository doesn't exist, etc.

It seems to me that the right behavior would be to store the return value of the system call, and raise an exception if appropriate. See https://github.com/technicalpickles/homesick/blob/master/lib/homesick/actions.rb#L16

**Comment by JCook21** [comment]
Closing this as homesick now checks that a minimum required version of Git is installed.
