### ISSUE TITLE
The shortcut `homesick technicalpickles/pickled-vim` clone and symlink automatically

### ISSUE THREAD

**Issue by christianbundy** [technicalpickles/homesick#58]
I think it would be great to have a shortcut feature, allowing you to quickly and easily grab your castle and get to work, rather than trying to remember how to homes[h]ick. cc: @andsens

**Comment by lloydde** [comment]
I came to homesick today. I was looking for a helper command to create my first castle.

**Comment by nicolasmccurdy** [comment]
From `homesick -h`:
    homesick generate PATH          # generate a homesick-ready git repo at PATH

**Comment by lloydde** [comment]
Thanks @nicolasmccurdy. I found it after your reply on twitter.
