### ISSUE TITLE
Symlink home dir and .homesick_subdir

### ISSUE THREAD

**Issue by vrachnis** [technicalpickles/homesick#86]
Hey there, I have an issue in my configuration with my home directory.

My home resides in /home/user but in fact the /home is a symlink to /usr/home.

The issue that I'm facing is that this breaks .homesick_subdir altogether. The contents of the subdir file are actually getting symlinked instead of merged and the symlink command tries to link the castle files to themselves:
`/usr/home/user/.homesick/repos/zsh-conf/home/.zsh.d/aliases.d -> /usr/home/user/.homesick/repos/zsh-conf/home/.zsh.d/aliases.d`.

I can work around this issue by overriding my HOME environment variable:

``` sh
HOME=/usr/home/user homesick symlink zsh-conf
```

**Comment by JCook21** [comment]
I believe this issue was fixed in #123 so I'm going to close this. Feel free to reopen if that's not the case.
