### ISSUE TITLE
Clone SSH URLs by default

### ISSUE THREAD

**Issue by nslater** [technicalpickles/homesick#90]
If you do this:

```
homesick clone nslater/dotfiles
```

Homesick clones using the HTTPS URL, meaning that if you `homesick cd dotfiles`, make some changes, and then try to push, you will be prompted for your password. (Assuming you as using SSH keys for authentication with GitHub.)

If you do this:

```
homesick clone git://github.com/nslater/dotfiles.git
```

And try the same, you actually get this:

```
fatal: remote error: 
  You can't push to git://github.com/nslater/dotfiles.git
  Use https://github.com/nslater/dotfiles.git
```

What I actually needed to do was:

```
homesick clone git@github.com:nslater/dotfiles.git
```

That works perfectly when you make changes from within your homesick dir.

I think this is important because I make all of my changes inside the homesick dir, because it saves a push, fetch, and rebase cycle between my main checkout, and the homesick clone. But it's frustrating that the default two documented methods produce a local clone that either prompts me for my password, or doesn't let me push.

**Comment by JCook21** [comment]
I'm going to close this due to the age and the lack of direction on whether SSH or HTTPS is really preferred. Feel free to reopen as needed.
